# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: todo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'todo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\x12\x0btodoPackage\"\x14\n\x12TodoRequestNoParam\"$\n\x08TodoItem\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\"1\n\tTodoItems\x12$\n\x05items\x18\x01 \x03(\x0b\x32\x15.todoPackage.TodoItem2\x8c\x01\n\x04Todo\x12<\n\nCreateTodo\x12\x15.todoPackage.TodoItem\x1a\x15.todoPackage.TodoItem\"\x00\x12\x46\n\tReadTodos\x12\x1f.todoPackage.TodoRequestNoParam\x1a\x16.todoPackage.TodoItems\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TODOREQUESTNOPARAM']._serialized_start=27
  _globals['_TODOREQUESTNOPARAM']._serialized_end=47
  _globals['_TODOITEM']._serialized_start=49
  _globals['_TODOITEM']._serialized_end=85
  _globals['_TODOITEMS']._serialized_start=87
  _globals['_TODOITEMS']._serialized_end=136
  _globals['_TODO']._serialized_start=139
  _globals['_TODO']._serialized_end=279
# @@protoc_insertion_point(module_scope)
