# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import todo_pb2 as todo__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in todo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TodoStub(object):
    """
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTodo = channel.unary_unary(
                '/todoPackage.Todo/CreateTodo',
                request_serializer=todo__pb2.TodoItem.SerializeToString,
                response_deserializer=todo__pb2.TodoItem.FromString,
                _registered_method=True)
        self.ReadTodos = channel.unary_unary(
                '/todoPackage.Todo/ReadTodos',
                request_serializer=todo__pb2.TodoRequestNoParam.SerializeToString,
                response_deserializer=todo__pb2.TodoItems.FromString,
                _registered_method=True)


class TodoServicer(object):
    """
    """

    def CreateTodo(self, request, context):
        """create a todo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadTodos(self, request, context):
        """read to do
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TodoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTodo,
                    request_deserializer=todo__pb2.TodoItem.FromString,
                    response_serializer=todo__pb2.TodoItem.SerializeToString,
            ),
            'ReadTodos': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadTodos,
                    request_deserializer=todo__pb2.TodoRequestNoParam.FromString,
                    response_serializer=todo__pb2.TodoItems.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'todoPackage.Todo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('todoPackage.Todo', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Todo(object):
    """
    """

    @staticmethod
    def CreateTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/todoPackage.Todo/CreateTodo',
            todo__pb2.TodoItem.SerializeToString,
            todo__pb2.TodoItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadTodos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/todoPackage.Todo/ReadTodos',
            todo__pb2.TodoRequestNoParam.SerializeToString,
            todo__pb2.TodoItems.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
